name: Documentation
on:
  push:
    branches:
      - master
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install zensical
        run: pip install zensical

      - name: Build documentation
        run: zensical build --clean

      - uses: actions/upload-pages-artifact@v4
        with:
          path: site


  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
